services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:3000' # Expose the frontend on port 80 of the host
    networks:
        - basenet

networks:
    basenet: